version: '3.8'

services:
  mcp-youtube-transcript:
    build:
      context: .
      dockerfile: Dockerfile.railway
    ports:
      # Map host port 8000 to container port 8000
      - "8000:8000"
    environment:
      # Set PORT to match the exposed port
      - PORT=8000
      # Optional: Set response limit (default: 50000)
      # - RESPONSE_LIMIT=50000
      # Optional: Proxy configuration
      # - WEBSHARE_PROXY_USERNAME=your_username
      # - WEBSHARE_PROXY_PASSWORD=your_password
      # - HTTP_PROXY=http://proxy.example.com:8080
      # - HTTPS_PROXY=https://proxy.example.com:8080
    restart: unless-stopped
    # Health check to ensure service is running
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# To run locally:
# docker-compose up -d
#
# To stop:
# docker-compose down
#
# To view logs:
# docker-compose logs -f
#
# To rebuild after code changes:
# docker-compose up -d --build
