version: '3.8'

services:
  mcp-youtube-transcript:
    build:
      context: .
      dockerfile: Dockerfile.n8n
    ports:
      # Map host port 8000 to container port 8000
      - "8000:8000"
    environment:
      # Set PORT to match the exposed port
      - PORT=8000
      # Optional: Set response limit (default: 50000)
      # - RESPONSE_LIMIT=50000
      # Optional: Proxy configuration
      # - WEBSHARE_PROXY_USERNAME=your_username
      # - WEBSHARE_PROXY_PASSWORD=your_password
      # - HTTP_PROXY=http://proxy.example.com:8080
      # - HTTPS_PROXY=https://proxy.example.com:8080
    restart: unless-stopped

# To run for n8n integration:
# docker-compose -f docker-compose.n8n.yml up -d
#
# The server will be available at: http://localhost:8000
# Or if deployed: http://your-server-ip:8000
#
# In n8n MCP Client Tool, use:
# SSE Endpoint: http://your-server-ip:8000
#
# To stop:
# docker-compose -f docker-compose.n8n.yml down
#
# To view logs:
# docker-compose -f docker-compose.n8n.yml logs -f
