[project]
name = "mcp-youtube-transcript"
version = "0.1.0"
description = "MCP server retrieving transcripts of YouTube videos"
readme = "README.md"
authors = [
    { name = "Junpei Kawamoto", email = "kawamoto.junpei@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "mcp>=1.2.1",
    "youtube-transcript-api>=0.6.3",
]

[project.scripts]
mcp-youtube-transcript = "mcp_youtube_transcript:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]

